version: '3'

services:

  portainer:
    image: portainer/portainer
    ports:
     - 9000:9000
    networks:
      backend:
        aliases:
          - portainer_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceName=portainer_portainer
        - com.df.serviceDomain=portainer.contextpc.com
        - com.df.port=9000
        - com.df.httpsOnly=true
      replicas: 1

networks:
  backend:
    external: true

volumes:
  portainer:
    external: true
